Repository tipi-tapi/ai-paint-today-BE, pull requests merged in 2023-07, with the labels that each got.

#94 광고리워드 엔티티, 광고 등록 API, 리워드 사용 메소드 추가
  src/main/java/tipitapi/drawmytoday/adreward/controller/AdRewardController.java
  src/main/java/tipitapi/drawmytoday/adreward/domain/AdReward.java
  src/main/java/tipitapi/drawmytoday/adreward/repository/AdRewardRepository.java
  src/main/java/tipitapi/drawmytoday/adreward/service/AdRewardService.java
  src/main/java/tipitapi/drawmytoday/adreward/service/UseAdRewardService.java
  src/main/java/tipitapi/drawmytoday/common/config/SwaggerConfiguration.java
  src/main/java/tipitapi/drawmytoday/user/service/ValidateUserService.java
  src/test/java/tipitapi/drawmytoday/adreward/repository/AdRewardRepositoryTest.java
  src/test/java/tipitapi/drawmytoday/adreward/service/AdRewardServiceTest.java
  src/test/java/tipitapi/drawmytoday/adreward/service/UseAdRewardServiceTest.java
  src/test/java/tipitapi/drawmytoday/user/repository/UserRepositoryTest.java
  src/test/resources/tipitapi/drawmytoday/adreward/repository/ExpiredAdReward.sql
  src/test/resources/tipitapi/drawmytoday/adreward/repository/ValidAdReward.sql
Labels: ✨ Feature

#96 health check api 및 swagger 에러 수정
  src/main/java/tipitapi/drawmytoday/common/config/SecurityConfig.java
  src/main/java/tipitapi/drawmytoday/health/controller/HealthCheckController.java
  src/main/java/tipitapi/drawmytoday/oauth/controller/AuthController.java
Labels: 🔨 Refactor, ⚡ Fix

#98 http response시 빈 배열일 경우 빈 배열을 반환하도록 변경
  src/main/java/tipitapi/drawmytoday/common/response/SuccessResponse.java
  src/test/java/tipitapi/drawmytoday/response/SuccessResponseTest.java
Labels: 🔨 Refactor

#101 테스트용 SQL 파일에서 AdType 삭제
  src/test/resources/tipitapi/drawmytoday/adreward/repository/ExpiredAdReward.sql
  src/test/resources/tipitapi/drawmytoday/adreward/repository/ValidAdReward.sql
Labels: 🐞 Bug

#102 테스트용 SQL 파일에서 AdType 삭제
  src/test/resources/tipitapi/drawmytoday/adreward/repository/ExpiredAdReward.sql
  src/test/resources/tipitapi/drawmytoday/adreward/repository/ValidAdReward.sql
Labels: 🐞 Bug

#104 DiaryServcieTest 일부 mock 추가
  src/test/java/tipitapi/drawmytoday/diary/service/DiaryServiceTest.java
Labels: 🐞 Bug

#105 DiaryServcieTest 일부 mock 추가
  src/test/java/tipitapi/drawmytoday/diary/service/DiaryServiceTest.java
Labels: 🐞 Bug

#107 일기 생성시, 테스트 용으로 생성할 수 있는 기능 추가
  src/main/java/tipitapi/drawmytoday/diary/controller/DiaryController.java
  src/main/java/tipitapi/drawmytoday/diary/service/CreateDiaryService.java
Labels: ⚡ Fix, ✨ Feature

#111 테스트 없이 빌드하도록 useJUnitPlatform 주석 처리
  build.gradle
Labels: 🌏 Deploy&Infra, ✅ Test, 🐞 Bug

#115 Jacoco 도입 및 컨트롤러단 단위테스트 구현
  build.gradle
  src/main/java/tipitapi/drawmytoday/DrawMyTodayApplication.java
  src/main/java/tipitapi/drawmytoday/common/config/DevConfig.java
  src/main/java/tipitapi/drawmytoday/common/exception/GlobalExceptionHandler.java
  src/main/java/tipitapi/drawmytoday/common/validator/CustomCollectionValidator.java
  src/main/java/tipitapi/drawmytoday/dev/controller/DevelopController.java
  src/main/java/tipitapi/drawmytoday/diary/controller/DiaryController.java
  src/main/java/tipitapi/drawmytoday/diary/dto/CreateDiaryRequest.java
  src/main/java/tipitapi/drawmytoday/emotion/controller/EmotionController.java
  src/test/java/tipitapi/drawmytoday/adreward/controller/AdRewardControllerTest.java
  src/test/java/tipitapi/drawmytoday/common/controller/ControllerTestSetup.java
  src/test/java/tipitapi/drawmytoday/common/controller/WithCustomUser.java
  src/test/java/tipitapi/drawmytoday/common/controller/WithCustomUserSecurityContextFactory.java
  src/test/java/tipitapi/drawmytoday/dev/controller/DevelopControllerTest.java
  src/test/java/tipitapi/drawmytoday/diary/controller/DiaryControllerTest.java
  src/test/java/tipitapi/drawmytoday/emotion/controller/EmotionControllerTest.java
  src/test/java/tipitapi/drawmytoday/health/controller/HealthCheckControllerTest.java
  src/test/java/tipitapi/drawmytoday/oauth/controller/AuthControllerTest.java
Labels: ✅ Test, ⚡ Fix

#119 일기 생성시 빈 키워드를 받으면 키워드 자리에 Emotional을 작성하도록 수정
  src/main/java/tipitapi/drawmytoday/diary/service/PromptTextService.java
  src/test/java/tipitapi/drawmytoday/diary/service/PromptTextServiceTest.java
Labels: ✨ Feature

#120 관리자용 일기 이미지/프롬프트 목록 조회 API 추가
  src/main/java/tipitapi/drawmytoday/admin/controller/AdminController.java
  src/main/java/tipitapi/drawmytoday/admin/dto/GetDiaryAdminResponse.java
  src/main/java/tipitapi/drawmytoday/admin/service/AdminService.java
  src/main/java/tipitapi/drawmytoday/common/config/SwaggerConfiguration.java
  src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
  src/main/java/tipitapi/drawmytoday/diary/dto/DiaryForMonitorQueryResponse.java
  src/main/java/tipitapi/drawmytoday/diary/repository/DiaryRepository.java
  src/main/java/tipitapi/drawmytoday/diary/service/AdminDiaryService.java
  src/main/java/tipitapi/drawmytoday/user/domain/User.java
  src/main/java/tipitapi/drawmytoday/user/domain/UserRole.java
  src/main/java/tipitapi/drawmytoday/user/exception/UserAccessDeniedException.java
  src/main/java/tipitapi/drawmytoday/user/service/ValidateUserService.java
  src/test/java/tipitapi/drawmytoday/admin/controller/AdminControllerTest.java
  src/test/java/tipitapi/drawmytoday/admin/service/AdminServiceTest.java
  src/test/java/tipitapi/drawmytoday/common/testdata/TestUser.java
  src/test/java/tipitapi/drawmytoday/diary/repository/DiaryRepositoryTest.java
  src/test/java/tipitapi/drawmytoday/diary/service/AdminDiaryServiceTest.java
  src/test/resources/tipitapi/drawmytoday/diary/repository/GetAllDiariesForMonitorAsPageTest.sql
Labels: ✨ Feature

#122 관리자용 일기 목록 조회시 이미지 S3 URL로 발급
  src/main/java/tipitapi/drawmytoday/admin/service/AdminService.java
  src/main/resources/application.yml
Labels: ⚡ Fix, 🐞 Bug

#121 일기 생성시 이전 날짜 일기 생성 가능하도록 수정
  src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
  src/main/java/tipitapi/drawmytoday/diary/controller/DiaryController.java
  src/main/java/tipitapi/drawmytoday/diary/dto/CreateDiaryRequest.java
  src/main/java/tipitapi/drawmytoday/diary/service/CreateDiaryService.java
  src/test/java/tipitapi/drawmytoday/diary/controller/DiaryControllerTest.java
  src/test/java/tipitapi/drawmytoday/diary/service/CreateDiaryServiceTest.java
Labels: ✅ Test, ✨ Feature

#124 자잘한 버그와 네이밍 수정
  src/main/java/tipitapi/drawmytoday/diary/controller/DiaryController.java
  src/main/java/tipitapi/drawmytoday/diary/repository/DiaryRepository.java
  src/main/java/tipitapi/drawmytoday/diary/service/CreateDiaryService.java
Labels: 🐞 Bug, 🧼 CleanUp

#126 :sparkles: feature: 특정 날짜 일기 존재 여부 조회 API 추가
  src/main/java/tipitapi/drawmytoday/common/utils/DateUtils.java
  src/main/java/tipitapi/drawmytoday/diary/controller/DiaryController.java
  src/main/java/tipitapi/drawmytoday/diary/dto/GetDiaryExistByDateResponse.java
  src/main/java/tipitapi/drawmytoday/diary/repository/DiaryRepository.java
  src/main/java/tipitapi/drawmytoday/diary/service/DiaryService.java
  src/test/java/tipitapi/drawmytoday/diary/controller/DiaryControllerTest.java
  src/test/java/tipitapi/drawmytoday/diary/repository/DiaryRepositoryTest.java
  src/test/java/tipitapi/drawmytoday/diary/service/DiaryServiceTest.java
Labels: ✨ Feature

#128 환경변수 cd 파일에 반영
  .github/workflows/cd.yml
Labels: ⚡ Fix

#127 Release 1.0.0
  .github/workflows/cd.yml
  build.gradle
  src/main/java/tipitapi/drawmytoday/DrawMyTodayApplication.java
  src/main/java/tipitapi/drawmytoday/admin/controller/AdminController.java
  src/main/java/tipitapi/drawmytoday/admin/dto/GetDiaryAdminResponse.java
  src/main/java/tipitapi/drawmytoday/admin/service/AdminService.java
  src/main/java/tipitapi/drawmytoday/common/config/DevConfig.java
  src/main/java/tipitapi/drawmytoday/common/config/SwaggerConfiguration.java
  src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
  src/main/java/tipitapi/drawmytoday/common/exception/GlobalExceptionHandler.java
  src/main/java/tipitapi/drawmytoday/common/utils/DateUtils.java
  src/main/java/tipitapi/drawmytoday/common/validator/CustomCollectionValidator.java
  src/main/java/tipitapi/drawmytoday/dev/controller/DevelopController.java
  src/main/java/tipitapi/drawmytoday/diary/controller/DiaryController.java
  src/main/java/tipitapi/drawmytoday/diary/dto/CreateDiaryRequest.java
  src/main/java/tipitapi/drawmytoday/diary/dto/DiaryForMonitorQueryResponse.java
  src/main/java/tipitapi/drawmytoday/diary/dto/GetDiaryExistByDateResponse.java
  src/main/java/tipitapi/drawmytoday/diary/repository/DiaryRepository.java
  src/main/java/tipitapi/drawmytoday/diary/service/AdminDiaryService.java
  src/main/java/tipitapi/drawmytoday/diary/service/CreateDiaryService.java
  src/main/java/tipitapi/drawmytoday/diary/service/DiaryService.java
  src/main/java/tipitapi/drawmytoday/emotion/controller/EmotionController.java
  src/main/java/tipitapi/drawmytoday/user/domain/User.java
  src/main/java/tipitapi/drawmytoday/user/domain/UserRole.java
  src/main/java/tipitapi/drawmytoday/user/exception/UserAccessDeniedException.java
  src/main/java/tipitapi/drawmytoday/user/service/ValidateUserService.java
  src/main/resources/application.yml
  src/test/java/tipitapi/drawmytoday/admin/controller/AdminControllerTest.java
  src/test/java/tipitapi/drawmytoday/admin/service/AdminServiceTest.java
  src/test/java/tipitapi/drawmytoday/adreward/controller/AdRewardControllerTest.java
  src/test/java/tipitapi/drawmytoday/common/controller/ControllerTestSetup.java
  src/test/java/tipitapi/drawmytoday/common/controller/WithCustomUser.java
  src/test/java/tipitapi/drawmytoday/common/controller/WithCustomUserSecurityContextFactory.java
  src/test/java/tipitapi/drawmytoday/common/testdata/TestUser.java
  src/test/java/tipitapi/drawmytoday/dev/controller/DevelopControllerTest.java
  src/test/java/tipitapi/drawmytoday/diary/controller/DiaryControllerTest.java
  src/test/java/tipitapi/drawmytoday/diary/repository/DiaryRepositoryTest.java
  src/test/java/tipitapi/drawmytoday/diary/service/AdminDiaryServiceTest.java
  src/test/java/tipitapi/drawmytoday/diary/service/CreateDiaryServiceTest.java
  src/test/java/tipitapi/drawmytoday/diary/service/DiaryServiceTest.java
  src/test/java/tipitapi/drawmytoday/emotion/controller/EmotionControllerTest.java
  src/test/java/tipitapi/drawmytoday/health/controller/HealthCheckControllerTest.java
  src/test/java/tipitapi/drawmytoday/oauth/controller/AuthControllerTest.java
  src/test/resources/tipitapi/drawmytoday/diary/repository/GetAllDiariesForMonitorAsPageTest.sql
Labels: 🌏 Deploy&Infra

#130 Admin 일기 목록 조회시 더미 이미지는 반환 안 되도록 수정 및 테스트 수정
  src/main/java/tipitapi/drawmytoday/diary/domain/Diary.java
  src/main/java/tipitapi/drawmytoday/diary/repository/DiaryRepository.java
  src/main/java/tipitapi/drawmytoday/diary/service/CreateDiaryService.java
  src/main/resources/application.yml
  src/test/java/tipitapi/drawmytoday/admin/service/AdminServiceTest.java
  src/test/java/tipitapi/drawmytoday/common/testdata/TestDiary.java
  src/test/java/tipitapi/drawmytoday/diary/controller/DiaryControllerTest.java
  src/test/java/tipitapi/drawmytoday/diary/repository/DiaryRepositoryTest.java
  src/test/java/tipitapi/drawmytoday/diary/service/CreateDiaryServiceTest.java
  src/test/resources/tipitapi/drawmytoday/diary/repository/GetAllDiariesForMonitorAsPageTest.sql
Labels: ✅ Test, ⚡ Fix

#134 Apple client secret 생성 로직 추가
  .github/workflows/cd.yml
  build.gradle
  src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
  src/main/java/tipitapi/drawmytoday/oauth/properties/AppleClientSecret.java
  src/main/java/tipitapi/drawmytoday/oauth/properties/ApplePrivateKey.java
  src/main/java/tipitapi/drawmytoday/oauth/properties/AppleProperties.java
  src/main/java/tipitapi/drawmytoday/oauth/service/AppleOAuthService.java
  src/main/resources/application-oauth.yml
  src/test/java/tipitapi/drawmytoday/oauth/integrate/ApplePropertiesTest.java
Labels: ✅ Test, ✨ Feature

#141 일기 생성 시 키워드가 없으면 eomtional이 아닌 emotions로 대체되도록 변경
  src/main/java/tipitapi/drawmytoday/diary/service/PromptTextService.java
Labels: 🔨 Refactor

#139 로그 레벨에 따른 파일 분리 및 로그 설정 추가
  .gitignore
  build.gradle
  src/main/java/tipitapi/drawmytoday/common/config/SecurityConfig.java
  src/main/java/tipitapi/drawmytoday/common/log/MDCRequestLoggingFilter.java
  src/main/resources/logback-spring.xml
Labels: ✨ Feature

#144 일기 생성 API와 관련된 diaryDate 필드 검증 방식 변경, 코드 아키텍처 리팩토링
  src/main/java/tipitapi/drawmytoday/common/validator/DiaryDateValidator.java
  src/main/java/tipitapi/drawmytoday/common/validator/ValidDiaryDate.java
  src/main/java/tipitapi/drawmytoday/diary/controller/DiaryController.java
  src/main/java/tipitapi/drawmytoday/diary/domain/Diary.java
  src/main/java/tipitapi/drawmytoday/diary/dto/CreateDiaryRequest.java
  src/main/java/tipitapi/drawmytoday/diary/service/CreateDiaryService.java
  src/main/java/tipitapi/drawmytoday/diary/service/ImageService.java
  src/test/java/tipitapi/drawmytoday/common/testdata/TestDiary.java
  src/test/java/tipitapi/drawmytoday/diary/controller/DiaryControllerTest.java
  src/test/java/tipitapi/drawmytoday/diary/service/CreateDiaryServiceTest.java
  src/test/java/tipitapi/drawmytoday/diary/service/ImageServiceTest.java
  src/test/java/tipitapi/drawmytoday/diary/service/PromptTextServiceTest.java
Labels: 🔨 Refactor, ✅ Test, ⚡ Fix, 🧼 CleanUp

#145 일기 프롬프트 생성시 keyword가 100자를 넘을 경우 자르도록 처리
  src/main/java/tipitapi/drawmytoday/diary/dto/CreateDiaryRequest.java
  src/main/java/tipitapi/drawmytoday/diary/service/PromptTextService.java
  src/test/java/tipitapi/drawmytoday/diary/controller/DiaryControllerTest.java
  src/test/java/tipitapi/drawmytoday/diary/service/PromptTextServiceTest.java
Labels: ⚡ Fix

#148 일기 조회 api에 lan 쿼리 파라미터 추가
  src/main/java/tipitapi/drawmytoday/common/config/WebConfig.java
  src/main/java/tipitapi/drawmytoday/common/converter/Language.java
  src/main/java/tipitapi/drawmytoday/common/converter/StringToLanguageConverter.java
  src/main/java/tipitapi/drawmytoday/diary/controller/DiaryController.java
  src/main/java/tipitapi/drawmytoday/diary/dto/GetDiaryResponse.java
  src/main/java/tipitapi/drawmytoday/diary/service/DiaryService.java
  src/main/java/tipitapi/drawmytoday/emotion/domain/Emotion.java
  src/test/java/tipitapi/drawmytoday/diary/controller/DiaryControllerTest.java
  src/test/java/tipitapi/drawmytoday/diary/service/DiaryServiceTest.java
Labels: ⚡ Fix, ✨ Feature

#149 Release 1.0.1
  .github/workflows/cd.yml
  .gitignore
  build.gradle
  src/main/java/tipitapi/drawmytoday/common/config/SecurityConfig.java
  src/main/java/tipitapi/drawmytoday/common/config/WebConfig.java
  src/main/java/tipitapi/drawmytoday/common/converter/Language.java
  src/main/java/tipitapi/drawmytoday/common/converter/StringToLanguageConverter.java
  src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
  src/main/java/tipitapi/drawmytoday/common/log/MDCRequestLoggingFilter.java
  src/main/java/tipitapi/drawmytoday/common/validator/DiaryDateValidator.java
  src/main/java/tipitapi/drawmytoday/common/validator/ValidDiaryDate.java
  src/main/java/tipitapi/drawmytoday/diary/controller/DiaryController.java
  src/main/java/tipitapi/drawmytoday/diary/domain/Diary.java
  src/main/java/tipitapi/drawmytoday/diary/dto/CreateDiaryRequest.java
  src/main/java/tipitapi/drawmytoday/diary/dto/GetDiaryResponse.java
  src/main/java/tipitapi/drawmytoday/diary/repository/DiaryRepository.java
  src/main/java/tipitapi/drawmytoday/diary/service/CreateDiaryService.java
  src/main/java/tipitapi/drawmytoday/diary/service/DiaryService.java
  src/main/java/tipitapi/drawmytoday/diary/service/ImageService.java
  src/main/java/tipitapi/drawmytoday/diary/service/PromptTextService.java
  src/main/java/tipitapi/drawmytoday/emotion/domain/Emotion.java
  src/main/java/tipitapi/drawmytoday/oauth/properties/AppleClientSecret.java
  src/main/java/tipitapi/drawmytoday/oauth/properties/ApplePrivateKey.java
  src/main/java/tipitapi/drawmytoday/oauth/properties/AppleProperties.java
  src/main/java/tipitapi/drawmytoday/oauth/service/AppleOAuthService.java
  src/main/java/tipitapi/drawmytoday/oauth/service/GoogleOAuthService.java
  src/main/resources/application-oauth.yml
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
  src/test/java/tipitapi/drawmytoday/admin/service/AdminServiceTest.java
  src/test/java/tipitapi/drawmytoday/common/testdata/TestDiary.java
  src/test/java/tipitapi/drawmytoday/diary/controller/DiaryControllerTest.java
  src/test/java/tipitapi/drawmytoday/diary/repository/DiaryRepositoryTest.java
  src/test/java/tipitapi/drawmytoday/diary/service/CreateDiaryServiceTest.java
  src/test/java/tipitapi/drawmytoday/diary/service/DiaryServiceTest.java
  src/test/java/tipitapi/drawmytoday/diary/service/ImageServiceTest.java
  src/test/java/tipitapi/drawmytoday/diary/service/PromptTextServiceTest.java
  src/test/java/tipitapi/drawmytoday/oauth/integrate/ApplePropertiesTest.java
  src/test/resources/tipitapi/drawmytoday/diary/repository/GetAllDiariesForMonitorAsPageTest.sql
Labels: 🌏 Deploy&Infra

#150 cd ios private key로 수정
  .github/workflows/cd.yml
Labels: 🐞 Bug

#151 cd ios private key로 수정
  .github/workflows/cd.yml
Labels: 🐞 Bug
