Repository tipi-tapi/ai-paint-today-BE, pull requests merged in 2023-05, with the labels that each got.

#9 JWT, OAuth 구현
  .editorconfig
  build.gradle
  src/main/java/tipitapi/drawmytoday/common/config/SecurityConfig.java
  src/main/java/tipitapi/drawmytoday/common/config/SwaggerConfiguration.java
  src/main/java/tipitapi/drawmytoday/common/exception/BusinessException.java
  src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
  src/main/java/tipitapi/drawmytoday/common/resolver/AuthUser.java
  src/main/java/tipitapi/drawmytoday/common/resolver/AuthUserArgumentResolver.java
  src/main/java/tipitapi/drawmytoday/common/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/tipitapi/drawmytoday/common/security/jwt/JwtAuthenticationFilter.java
  src/main/java/tipitapi/drawmytoday/common/security/jwt/JwtAuthenticationToken.java
  src/main/java/tipitapi/drawmytoday/common/security/jwt/JwtProperties.java
  src/main/java/tipitapi/drawmytoday/common/security/jwt/JwtTokenInfo.java
  src/main/java/tipitapi/drawmytoday/common/security/jwt/JwtTokenProvider.java
  src/main/java/tipitapi/drawmytoday/common/security/jwt/exception/ExpiredAccessTokenException.java
  src/main/java/tipitapi/drawmytoday/common/security/jwt/exception/ExpiredRefreshTokenException.java
  src/main/java/tipitapi/drawmytoday/common/security/jwt/exception/InvalidTokenException.java
  src/main/java/tipitapi/drawmytoday/common/security/jwt/exception/TokenException.java
  src/main/java/tipitapi/drawmytoday/common/security/jwt/exception/TokenNotFoundException.java
  src/main/java/tipitapi/drawmytoday/diary/controller/DiaryController.java
  src/main/java/tipitapi/drawmytoday/oauth/controller/AuthController.java
  src/main/java/tipitapi/drawmytoday/oauth/domain/Auth.java
  src/main/java/tipitapi/drawmytoday/oauth/dto/AppleIdToken.java
  src/main/java/tipitapi/drawmytoday/oauth/dto/OAuthAccessToken.java
  src/main/java/tipitapi/drawmytoday/oauth/dto/OAuthUserProfile.java
  src/main/java/tipitapi/drawmytoday/oauth/dto/RequestAppleLogin.java
  src/main/java/tipitapi/drawmytoday/oauth/dto/ResponseAccessToken.java
  src/main/java/tipitapi/drawmytoday/oauth/dto/ResponseJwtToken.java
  src/main/java/tipitapi/drawmytoday/oauth/properties/AppleProperties.java
  src/main/java/tipitapi/drawmytoday/oauth/properties/GoogleProperties.java
  src/main/java/tipitapi/drawmytoday/oauth/repository/AuthRepository.java
  src/main/java/tipitapi/drawmytoday/oauth/service/AppleOAuthService.java
  src/main/java/tipitapi/drawmytoday/oauth/service/GoogleOAuthService.java
  src/main/java/tipitapi/drawmytoday/user/controller/AuthController.java
  src/main/java/tipitapi/drawmytoday/user/domain/OAuthType.java
  src/main/java/tipitapi/drawmytoday/user/domain/User.java
  src/main/java/tipitapi/drawmytoday/user/domain/UserRole.java
  src/main/java/tipitapi/drawmytoday/user/repository/UserRepository.java
  src/main/resources/application-develop.yml
  src/main/resources/application-oauth.yml
  src/main/resources/application.yml
Labels: ✨ Feature

#18 EmotionRecord 삭제, 감정-일기 관계 추가, 일기 Hard Delete 설정 추가
  src/main/java/tipitapi/drawmytoday/diary/domain/Diary.java
  src/main/java/tipitapi/drawmytoday/diary/domain/EmotionRecord.java
  src/main/java/tipitapi/drawmytoday/diary/dto/DiaryResponse.java
  src/main/java/tipitapi/drawmytoday/diary/repository/EmotionRecordRepository.java
  src/main/java/tipitapi/drawmytoday/diary/service/DiaryService.java
  src/main/java/tipitapi/drawmytoday/diary/service/EmotionRecordService.java
Labels: ✨ Feature

#19 특정 일기 조회 API, 테스트 추가
  build.gradle
  src/main/java/tipitapi/drawmytoday/DrawMyTodayApplication.java
  src/main/java/tipitapi/drawmytoday/common/config/WebConfig.java
  src/main/java/tipitapi/drawmytoday/common/response/SuccessResponse.java
  src/main/java/tipitapi/drawmytoday/diary/controller/DiaryController.java
  src/main/java/tipitapi/drawmytoday/diary/domain/Image.java
  src/main/java/tipitapi/drawmytoday/diary/dto/DiaryResponse.java
  src/main/java/tipitapi/drawmytoday/diary/dto/GetDiaryResponse.java
  src/main/java/tipitapi/drawmytoday/diary/service/DiaryService.java
  src/main/java/tipitapi/drawmytoday/emotion/repository/EmotionRepository.java
  src/main/java/tipitapi/drawmytoday/user/service/ValidateUserService.java
  src/test/java/tipitapi/drawmytoday/common/BaseRepositoryTest.java
  src/test/java/tipitapi/drawmytoday/common/testdata/TestDiary.java
  src/test/java/tipitapi/drawmytoday/common/testdata/TestEmotion.java
  src/test/java/tipitapi/drawmytoday/common/testdata/TestImage.java
  src/test/java/tipitapi/drawmytoday/common/testdata/TestUser.java
  src/test/java/tipitapi/drawmytoday/diary/repository/DiaryRepositoryTest.java
  src/test/java/tipitapi/drawmytoday/diary/repository/ImageRepositoryTest.java
  src/test/java/tipitapi/drawmytoday/diary/service/DiaryServiceTest.java
  src/test/java/tipitapi/drawmytoday/diary/service/ImageServiceTest.java
  src/test/resources/application.yml
Labels: ✅ Test, ✨ Feature

#22 인프라 구축 및 cd(github actions) 구현
  .github/workflows/cd.yml
  src/main/resources/application-prod.yml
Labels: 🌏 Deploy&Infra
