Repository tipi-tapi/ai-paint-today-BE, pull requests merged in 2023-09, with the labels that each got.

#227 Dalle 요청 로직 분리 및 서비스단 테스트 추가
  src/main/java/tipitapi/drawmytoday/domain/dalle/exception/DallEPolicyViolationException.java
  src/main/java/tipitapi/drawmytoday/domain/dalle/service/DallERequestService.java
  src/main/java/tipitapi/drawmytoday/domain/dalle/service/DallEService.java
  src/test/java/tipitapi/drawmytoday/domain/dalle/service/DallERequestServiceTest.java
  src/test/java/tipitapi/drawmytoday/domain/dalle/service/DallEServiceTest.java
Labels: 🔨 Refactor, ✅ Test

#229 Release 1.1.4
  build.gradle
  src/main/java/tipitapi/drawmytoday/common/cache/CacheConst.java
  src/main/java/tipitapi/drawmytoday/common/cache/CacheType.java
  src/main/java/tipitapi/drawmytoday/common/config/CacheConfig.java
  src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
  src/main/java/tipitapi/drawmytoday/common/utils/HeaderUtils.java
  src/main/java/tipitapi/drawmytoday/domain/dalle/exception/DallEPolicyViolationException.java
  src/main/java/tipitapi/drawmytoday/domain/dalle/service/DallERequestService.java
  src/main/java/tipitapi/drawmytoday/domain/dalle/service/DallEService.java
  src/main/java/tipitapi/drawmytoday/domain/emotion/controller/EmotionController.java
  src/main/java/tipitapi/drawmytoday/domain/emotion/dto/GetActiveEmotionsResponse.java
  src/main/java/tipitapi/drawmytoday/domain/emotion/service/EmotionService.java
  src/main/java/tipitapi/drawmytoday/domain/oauth/controller/AuthController.java
  src/main/java/tipitapi/drawmytoday/domain/oauth/domain/Auth.java
  src/main/java/tipitapi/drawmytoday/domain/oauth/service/AppleOAuthService.java
  src/main/java/tipitapi/drawmytoday/domain/oauth/service/GoogleOAuthService.java
  src/main/java/tipitapi/drawmytoday/domain/user/domain/User.java
  src/main/java/tipitapi/drawmytoday/domain/user/service/UserService.java
  src/test/java/tipitapi/drawmytoday/common/response/SuccessResponseTest.java
  src/test/java/tipitapi/drawmytoday/common/testdata/TestAuth.java
  src/test/java/tipitapi/drawmytoday/common/testdata/TestUser.java
  src/test/java/tipitapi/drawmytoday/domain/dalle/service/DallERequestServiceTest.java
  src/test/java/tipitapi/drawmytoday/domain/dalle/service/DallEServiceTest.java
  src/test/java/tipitapi/drawmytoday/domain/diary/service/EmotionServiceTest.java
  src/test/java/tipitapi/drawmytoday/domain/emotion/controller/EmotionControllerTest.java
  src/test/java/tipitapi/drawmytoday/domain/oauth/service/AppleOAuthServiceTest.java
  src/test/java/tipitapi/drawmytoday/domain/oauth/service/GoogleOAuthServiceTest.java
  src/test/java/tipitapi/drawmytoday/domain/oauth/service/OAuthServiceTest.java
  src/test/java/tipitapi/drawmytoday/domain/user/repository/UserRepositoryTest.java
  src/test/resources/tipitapi/drawmytoday/domain/adreward/repository/ExpiredAdReward.sql
  src/test/resources/tipitapi/drawmytoday/domain/adreward/repository/ValidAdReward.sql
  src/test/resources/tipitapi/drawmytoday/domain/diary/repository/GetDiariesForMonitorAsPageTest.sql
  src/test/resources/tipitapi/drawmytoday/domain/ticket/repository/ValidTicket.sql
Labels: 🌏 Deploy&Infra

#233 회원가입시 티켓 1장만 발급되도록 변경
  src/main/java/tipitapi/drawmytoday/domain/ticket/service/TicketService.java
  src/test/java/tipitapi/drawmytoday/domain/ticket/service/TicketServiceTest.java
Labels: 🌏 Deploy&Infra

#234 회원가입시 티켓 1장만 발급되도록 변경
  src/main/java/tipitapi/drawmytoday/domain/ticket/service/TicketService.java
  src/test/java/tipitapi/drawmytoday/domain/ticket/service/TicketServiceTest.java
Labels: 🔨 Refactor

#231 유저 그림 평가 기능 추가
  src/main/java/tipitapi/drawmytoday/common/resolver/AuthUser.java
  src/main/java/tipitapi/drawmytoday/domain/diary/controller/DiaryController.java
  src/main/java/tipitapi/drawmytoday/domain/diary/domain/Diary.java
  src/main/java/tipitapi/drawmytoday/domain/diary/domain/ReviewType.java
  src/main/java/tipitapi/drawmytoday/domain/diary/dto/ReviewDiaryRequest.java
  src/main/java/tipitapi/drawmytoday/domain/diary/service/DiaryService.java
  src/test/java/tipitapi/drawmytoday/domain/diary/controller/DiaryControllerTest.java
  src/test/java/tipitapi/drawmytoday/domain/diary/service/DiaryServiceTest.java
Labels: ✅ Test, ✨ Feature

#235 이미지 재생성 로직 구현
  src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
  src/main/java/tipitapi/drawmytoday/common/exception/GlobalExceptionHandler.java
  src/main/java/tipitapi/drawmytoday/domain/dalle/service/DallEService.java
  src/main/java/tipitapi/drawmytoday/domain/diary/controller/DiaryController.java
  src/main/java/tipitapi/drawmytoday/domain/diary/dto/GetDiaryResponse.java
  src/main/java/tipitapi/drawmytoday/domain/diary/dto/GetImageResponse.java
  src/main/java/tipitapi/drawmytoday/domain/diary/exception/PromptNotExistException.java
  src/main/java/tipitapi/drawmytoday/domain/diary/repository/ImageRepository.java
  src/main/java/tipitapi/drawmytoday/domain/diary/repository/PromptRepository.java
  src/main/java/tipitapi/drawmytoday/domain/diary/service/CreateDiaryService.java
  src/main/java/tipitapi/drawmytoday/domain/diary/service/DiaryService.java
  src/main/java/tipitapi/drawmytoday/domain/diary/service/ImageService.java
  src/main/java/tipitapi/drawmytoday/domain/diary/service/PromptService.java
  src/test/java/tipitapi/drawmytoday/common/BaseRepositoryTest.java
  src/test/java/tipitapi/drawmytoday/common/testdata/TestPrompt.java
  src/test/java/tipitapi/drawmytoday/domain/diary/controller/DiaryControllerTest.java
  src/test/java/tipitapi/drawmytoday/domain/diary/repository/ImageRepositoryTest.java
  src/test/java/tipitapi/drawmytoday/domain/diary/repository/PromptRepositoryTest.java
  src/test/java/tipitapi/drawmytoday/domain/diary/service/CreateDiaryServiceTest.java
  src/test/java/tipitapi/drawmytoday/domain/diary/service/DiaryServiceTest.java
Labels: 🔨 Refactor, ✅ Test, ✨ Feature

#239 이미지 재생성 작업시 발생한 버그 수정
  src/main/java/tipitapi/drawmytoday/domain/diary/controller/DiaryController.java
  src/test/java/tipitapi/drawmytoday/domain/diary/controller/DiaryControllerTest.java
Labels: 🐞 Bug

#241 r2 이미지 조회시 커스텀 url로 조회하도록 변경
  src/main/java/tipitapi/drawmytoday/domain/diary/service/AdminDiaryService.java
  src/main/java/tipitapi/drawmytoday/domain/diary/service/DiaryService.java
  src/main/java/tipitapi/drawmytoday/domain/r2/service/R2PreSignedService.java
Labels: 🐞 Bug

#240 Image Generator DallE -> Karlo 변경
  .github/workflows/cd.yml
  src/main/java/tipitapi/drawmytoday/common/config/ImageGenerateRestTemplateConfig.java
  src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
  src/main/java/tipitapi/drawmytoday/common/exception/GlobalExceptionHandler.java
  src/main/java/tipitapi/drawmytoday/domain/dalle/dto/CreateImageRequest.java
  src/main/java/tipitapi/drawmytoday/domain/dalle/exception/DallEException.java
  src/main/java/tipitapi/drawmytoday/domain/dalle/exception/DallEPolicyViolationException.java
  src/main/java/tipitapi/drawmytoday/domain/dalle/exception/DallERequestFailException.java
  src/main/java/tipitapi/drawmytoday/domain/dalle/exception/ImageInputStreamFailException.java
  src/main/java/tipitapi/drawmytoday/domain/diary/controller/DiaryController.java
  src/main/java/tipitapi/drawmytoday/domain/diary/service/CreateDiaryService.java
  src/main/java/tipitapi/drawmytoday/domain/generator/domain/dalle/dto/CreateDallEImageRequest.java
  src/main/java/tipitapi/drawmytoday/domain/generator/domain/dalle/dto/DallEBase64Response.java
  src/main/java/tipitapi/drawmytoday/domain/generator/domain/dalle/dto/DallEUrlResponse.java
  src/main/java/tipitapi/drawmytoday/domain/generator/domain/dalle/exception/DallEPolicyViolationException.java
  src/main/java/tipitapi/drawmytoday/domain/generator/domain/dalle/exception/DallERequestFailException.java
  src/main/java/tipitapi/drawmytoday/domain/generator/domain/dalle/service/DallERequestService.java
  src/main/java/tipitapi/drawmytoday/domain/generator/domain/dalle/service/DallEService.java
  src/main/java/tipitapi/drawmytoday/domain/generator/domain/karlo/dto/CreateKarloImageRequest.java
  src/main/java/tipitapi/drawmytoday/domain/generator/domain/karlo/dto/KarloImageUrlResponse.java
  src/main/java/tipitapi/drawmytoday/domain/generator/domain/karlo/dto/KarloUrlResponse.java
  src/main/java/tipitapi/drawmytoday/domain/generator/domain/karlo/exception/KarloRequestFailException.java
  src/main/java/tipitapi/drawmytoday/domain/generator/domain/karlo/service/KarloRequestService.java
  src/main/java/tipitapi/drawmytoday/domain/generator/domain/karlo/service/KarloService.java
  src/main/java/tipitapi/drawmytoday/domain/generator/dto/GeneratedImageAndPrompt.java
  src/main/java/tipitapi/drawmytoday/domain/generator/exception/ImageGeneratorException.java
  src/main/java/tipitapi/drawmytoday/domain/generator/exception/ImageInputStreamFailException.java
  src/main/java/tipitapi/drawmytoday/domain/generator/service/ImageGeneratorService.java
  src/main/resources/application-kakao.yml
  src/main/resources/application.yml
  src/test/java/tipitapi/drawmytoday/domain/diary/controller/DiaryControllerTest.java
  src/test/java/tipitapi/drawmytoday/domain/diary/service/CreateDiaryServiceTest.java
  src/test/java/tipitapi/drawmytoday/domain/diary/service/DiaryServiceTest.java
  src/test/java/tipitapi/drawmytoday/domain/generator/domain/dalle/service/DallERequestServiceTest.java
  src/test/java/tipitapi/drawmytoday/domain/generator/domain/dalle/service/DallEServiceTest.java
  src/test/resources/application.yml
Labels: 🔨 Refactor, ✅ Test, ✨ Feature

#246 Swagger 테스트 서버 도메인 이름 변경 및 테스트 일기 생성 시 티켓 소모하도록 변경
  src/main/java/tipitapi/drawmytoday/common/config/SwaggerConfiguration.java
  src/main/java/tipitapi/drawmytoday/domain/diary/service/CreateDiaryService.java
Labels: 🔨 Refactor

#248 이미지 개선을 위한 프롬프트 변경(emotions -> portrait)
  src/main/java/tipitapi/drawmytoday/domain/diary/service/PromptTextService.java
Labels: ✨ Feature

#251 이미지 삭제 API 추가 및 일기 조회 API 수정
  src/main/java/tipitapi/drawmytoday/common/config/SwaggerConfiguration.java
  src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
  src/main/java/tipitapi/drawmytoday/domain/diary/controller/ImageController.java
  src/main/java/tipitapi/drawmytoday/domain/diary/domain/Image.java
  src/main/java/tipitapi/drawmytoday/domain/diary/dto/GetImageResponse.java
  src/main/java/tipitapi/drawmytoday/domain/diary/exception/DiaryNeedsImageException.java
  src/main/java/tipitapi/drawmytoday/domain/diary/exception/SelectedImageDeletionDeniedException.java
  src/main/java/tipitapi/drawmytoday/domain/diary/repository/ImageQueryRepository.java
  src/main/java/tipitapi/drawmytoday/domain/diary/repository/ImageQueryRepositoryImpl.java
  src/main/java/tipitapi/drawmytoday/domain/diary/repository/ImageRepository.java
  src/main/java/tipitapi/drawmytoday/domain/diary/service/DiaryService.java
  src/main/java/tipitapi/drawmytoday/domain/diary/service/ImageService.java
  src/test/java/tipitapi/drawmytoday/domain/diary/controller/DiaryControllerTest.java
  src/test/java/tipitapi/drawmytoday/domain/diary/controller/ImageControllerTest.java
  src/test/java/tipitapi/drawmytoday/domain/diary/repository/ImageRepositoryTest.java
  src/test/java/tipitapi/drawmytoday/domain/diary/service/ImageServiceTest.java
Labels: ⚡ Fix, ✨ Feature
