Repository tipi-tapi/ai-paint-today-BE, pull requests merged in 2023-06, with the labels that each got.

#25 일기 생성 API, 이미지 S3 업로드 기능 추가
  build.gradle
  src/main/java/tipitapi/drawmytoday/common/config/OpenAIRestTemplateConfig.java
  src/main/java/tipitapi/drawmytoday/common/config/S3Config.java
  src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
  src/main/java/tipitapi/drawmytoday/common/exception/GlobalExceptionHandler.java
  src/main/java/tipitapi/drawmytoday/dalle/dto/CreateImageRequest.java
  src/main/java/tipitapi/drawmytoday/dalle/dto/DallEBase64Response.java
  src/main/java/tipitapi/drawmytoday/dalle/dto/DallEUrlResponse.java
  src/main/java/tipitapi/drawmytoday/dalle/exception/DallERequestFailException.java
  src/main/java/tipitapi/drawmytoday/dalle/exception/ImageInputStreamFailException.java
  src/main/java/tipitapi/drawmytoday/dalle/service/DallEService.java
  src/main/java/tipitapi/drawmytoday/diary/controller/DiaryController.java
  src/main/java/tipitapi/drawmytoday/diary/domain/Prompt.java
  src/main/java/tipitapi/drawmytoday/diary/dto/CreateDiaryRequest.java
  src/main/java/tipitapi/drawmytoday/diary/dto/CreateDiaryResponse.java
  src/main/java/tipitapi/drawmytoday/diary/repository/PromptRepository.java
  src/main/java/tipitapi/drawmytoday/diary/service/CreateDiaryService.java
  src/main/java/tipitapi/drawmytoday/diary/service/ImageService.java
  src/main/java/tipitapi/drawmytoday/diary/service/PromptService.java
  src/main/java/tipitapi/drawmytoday/emotion/exception/EmotionNotFoundException.java
  src/main/java/tipitapi/drawmytoday/emotion/service/ValidateEmotionService.java
  src/main/java/tipitapi/drawmytoday/s3/exception/S3FailedException.java
  src/main/java/tipitapi/drawmytoday/s3/service/S3Service.java
  src/main/resources/application-aws.yml
  src/main/resources/application-openai.yml
  src/main/resources/application.yml
Labels: 🔧 Setting, ✨ Feature

#28 마지막 일기 생성 시각 조회 API
  src/main/java/tipitapi/drawmytoday/diary/controller/DiaryController.java
  src/main/java/tipitapi/drawmytoday/diary/dto/GetLastCreationResponse.java
  src/main/java/tipitapi/drawmytoday/diary/repository/DiaryRepository.java
  src/main/java/tipitapi/drawmytoday/diary/service/DiaryService.java
  src/test/java/tipitapi/drawmytoday/common/testdata/TestDiary.java
  src/test/java/tipitapi/drawmytoday/diary/repository/DiaryRepositoryTest.java
  src/test/java/tipitapi/drawmytoday/diary/service/DiaryServiceTest.java
Labels: ✨ Feature

#30 :sparkles: feature: 일기 수정 API 추가
  src/main/java/tipitapi/drawmytoday/diary/controller/DiaryController.java
  src/main/java/tipitapi/drawmytoday/diary/domain/Diary.java
  src/main/java/tipitapi/drawmytoday/diary/dto/UpdateDiaryRequest.java
  src/main/java/tipitapi/drawmytoday/diary/service/DiaryService.java
  src/test/java/tipitapi/drawmytoday/diary/service/DiaryServiceTest.java
Labels: ✨ Feature

#37 일기 조회 API가 이미지에 대해 Full S3 Url을 반환하도록 수정
  src/main/java/tipitapi/drawmytoday/diary/dto/GetDiaryResponse.java
  src/main/java/tipitapi/drawmytoday/diary/service/DiaryService.java
  src/main/java/tipitapi/drawmytoday/s3/service/S3Util.java
Labels: ✨ Feature

#38 Release 0.0.1(dev)
  .github/workflows/cd.yml
Labels: 🌏 Deploy&Infra

#39 Release 0.0.2
  src/main/java/tipitapi/drawmytoday/diary/controller/DiaryController.java
  src/main/java/tipitapi/drawmytoday/diary/dto/GetDiaryResponse.java
  src/main/java/tipitapi/drawmytoday/diary/service/DiaryService.java
  src/main/java/tipitapi/drawmytoday/emotion/controller/EmotionController.java
  src/main/java/tipitapi/drawmytoday/emotion/dto/CreateEmotionRequest.java
  src/main/java/tipitapi/drawmytoday/emotion/dto/CreateEmotionResponse.java
  src/main/java/tipitapi/drawmytoday/emotion/dto/GetActiveEmotionsResponse.java
  src/main/java/tipitapi/drawmytoday/emotion/repository/EmotionRepository.java
  src/main/java/tipitapi/drawmytoday/emotion/service/EmotionService.java
  src/main/java/tipitapi/drawmytoday/s3/service/S3Util.java
  src/test/java/tipitapi/drawmytoday/common/testdata/TestEmotion.java
  src/test/java/tipitapi/drawmytoday/diary/repository/EmotionRepositoryTest.java
  src/test/java/tipitapi/drawmytoday/diary/service/EmotionServiceTest.java
Labels: 🌏 Deploy&Infra

#43 Swagger curl 요청 실패 문제 해결[배포]
  src/main/java/tipitapi/drawmytoday/common/config/SwaggerConfiguration.java
Labels: 🌏 Deploy&Infra, 🐞 Bug

#42 Swagger curl 요청 실패 문제 해결
  src/main/java/tipitapi/drawmytoday/common/config/SwaggerConfiguration.java
Labels: 🐞 Bug

#47 Feature/46
  src/main/java/tipitapi/drawmytoday/diary/service/DiaryService.java
  src/main/java/tipitapi/drawmytoday/s3/service/S3PreSignedService.java
  src/main/java/tipitapi/drawmytoday/s3/service/S3Service.java
  src/main/java/tipitapi/drawmytoday/s3/service/S3Util.java
Labels: ⚡ Fix, ✨ Feature

#49 createEmotions 메소드 Transactional 적용
  src/main/java/tipitapi/drawmytoday/emotion/service/EmotionService.java
Labels: 🐞 Bug

#51 소셜로그인 오류 해결 및 리팩토링
  src/main/java/tipitapi/drawmytoday/common/config/SecurityConfig.java
  src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
  src/main/java/tipitapi/drawmytoday/common/exception/GlobalExceptionHandler.java
  src/main/java/tipitapi/drawmytoday/common/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/tipitapi/drawmytoday/common/security/jwt/JwtAuthenticationFilter.java
  src/main/java/tipitapi/drawmytoday/oauth/controller/AuthController.java
  src/main/java/tipitapi/drawmytoday/oauth/domain/Auth.java
  src/main/java/tipitapi/drawmytoday/oauth/dto/AppleIdToken.java
  src/main/java/tipitapi/drawmytoday/oauth/dto/RequestAppleLogin.java
  src/main/java/tipitapi/drawmytoday/oauth/exception/OAuthNotFoundException.java
  src/main/java/tipitapi/drawmytoday/oauth/service/AppleOAuthService.java
  src/main/java/tipitapi/drawmytoday/oauth/service/GoogleOAuthService.java
  src/main/java/tipitapi/drawmytoday/oauth/service/OAuthService.java
  src/main/java/tipitapi/drawmytoday/user/domain/User.java
  src/main/java/tipitapi/drawmytoday/user/exception/DuplicateUserException.java
  src/main/java/tipitapi/drawmytoday/user/repository/UserRepository.java
  src/main/java/tipitapi/drawmytoday/user/service/UserService.java
  src/main/java/tipitapi/drawmytoday/user/service/ValidateUserService.java
Labels: 🔨 Refactor, ⚡ Fix

#66 :sparkles: feature: 감정 목록 조회 API 언어 파라미터 추가
  src/main/java/tipitapi/drawmytoday/emotion/controller/EmotionController.java
  src/main/java/tipitapi/drawmytoday/emotion/dto/GetActiveEmotionsResponse.java
  src/main/java/tipitapi/drawmytoday/emotion/service/EmotionService.java
  src/test/java/tipitapi/drawmytoday/diary/service/EmotionServiceTest.java
Labels: ✨ Feature

#68 RestClientException 발생시 GlobalExceptionHandler가 공통적인 예외로 핸들링하도록 수정
  src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
  src/main/java/tipitapi/drawmytoday/common/exception/GlobalExceptionHandler.java
Labels: 🐞 Bug

#72 Release 0.0.3
  src/main/java/tipitapi/drawmytoday/common/config/SecurityConfig.java
  src/main/java/tipitapi/drawmytoday/common/config/SwaggerConfiguration.java
  src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
  src/main/java/tipitapi/drawmytoday/common/exception/GlobalExceptionHandler.java
  src/main/java/tipitapi/drawmytoday/common/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/tipitapi/drawmytoday/common/security/jwt/JwtAuthenticationFilter.java
  src/main/java/tipitapi/drawmytoday/common/security/jwt/JwtProperties.java
  src/main/java/tipitapi/drawmytoday/common/security/jwt/JwtTokenProvider.java
  src/main/java/tipitapi/drawmytoday/common/security/jwt/JwtType.java
  src/main/java/tipitapi/drawmytoday/common/utils/HeaderUtils.java
  src/main/java/tipitapi/drawmytoday/diary/controller/DiaryController.java
  src/main/java/tipitapi/drawmytoday/diary/domain/Diary.java
  src/main/java/tipitapi/drawmytoday/diary/dto/GetDiaryResponse.java
  src/main/java/tipitapi/drawmytoday/diary/repository/PromptRepository.java
  src/main/java/tipitapi/drawmytoday/diary/service/CreateDiaryService.java
  src/main/java/tipitapi/drawmytoday/diary/service/DiaryService.java
  src/main/java/tipitapi/drawmytoday/diary/service/PromptService.java
  src/main/java/tipitapi/drawmytoday/diary/service/ValidateDiaryService.java
  src/main/java/tipitapi/drawmytoday/emotion/controller/EmotionController.java
  src/main/java/tipitapi/drawmytoday/emotion/dto/GetActiveEmotionsResponse.java
  src/main/java/tipitapi/drawmytoday/emotion/service/EmotionService.java
  src/main/java/tipitapi/drawmytoday/oauth/controller/AuthController.java
  src/main/java/tipitapi/drawmytoday/oauth/domain/Auth.java
  src/main/java/tipitapi/drawmytoday/oauth/dto/AppleIdToken.java
  src/main/java/tipitapi/drawmytoday/oauth/dto/RequestAppleLogin.java
  src/main/java/tipitapi/drawmytoday/oauth/exception/OAuthNotFoundException.java
  src/main/java/tipitapi/drawmytoday/oauth/service/AppleOAuthService.java
  src/main/java/tipitapi/drawmytoday/oauth/service/GoogleOAuthService.java
  src/main/java/tipitapi/drawmytoday/oauth/service/OAuthService.java
  src/main/java/tipitapi/drawmytoday/s3/service/S3PreSignedService.java
  src/main/java/tipitapi/drawmytoday/s3/service/S3Service.java
  src/main/java/tipitapi/drawmytoday/s3/service/S3Util.java
  src/main/java/tipitapi/drawmytoday/user/domain/User.java
  src/main/java/tipitapi/drawmytoday/user/exception/DuplicateUserException.java
  src/main/java/tipitapi/drawmytoday/user/repository/UserRepository.java
  src/main/java/tipitapi/drawmytoday/user/service/UserService.java
  src/main/java/tipitapi/drawmytoday/user/service/ValidateUserService.java
  src/main/resources/application-test.yml
  src/test/java/tipitapi/drawmytoday/common/BaseRepositoryTest.java
  src/test/java/tipitapi/drawmytoday/common/testdata/TestDiary.java
  src/test/java/tipitapi/drawmytoday/diary/repository/DiaryRepositoryTest.java
  src/test/java/tipitapi/drawmytoday/diary/repository/ImageRepositoryTest.java
  src/test/java/tipitapi/drawmytoday/diary/service/DiaryServiceTest.java
  src/test/java/tipitapi/drawmytoday/diary/service/EmotionServiceTest.java
  src/test/java/tipitapi/drawmytoday/diary/service/ValidateDiaryServiceTest.java
Labels: 🌏 Deploy&Infra

#76 S3Presigner 객체 생성시 aws credential과 함께 빌드
  src/main/java/tipitapi/drawmytoday/s3/service/S3PreSignedService.java
Labels: 🐞 Bug

#78 월별 일기 조회 API가 반환하는 이미지 URL을 FULL 이미지 URL로 반환하도록 수정
  src/main/java/tipitapi/drawmytoday/diary/dto/GetMonthlyDiariesResponse.java
  src/main/java/tipitapi/drawmytoday/diary/service/DiaryService.java
Labels: ⚡ Fix, 🐞 Bug

#79 월별 일기 조회 API가 반환하는 이미지 URL을 FULL 이미지 URL로 반환하도록 수정
  src/main/java/tipitapi/drawmytoday/diary/dto/GetMonthlyDiariesResponse.java
  src/main/java/tipitapi/drawmytoday/diary/service/DiaryService.java
Labels: ⚡ Fix, 🐞 Bug

#80 validateUserWithDrawLimit 메소드의 NullPointerException 발생 문제 해결
  src/main/java/tipitapi/drawmytoday/user/service/ValidateUserService.java
Labels: 🐞 Bug

#81 validateUserWithDrawLimit 메소드의 NullPointerException 발생 문제 해결
  src/main/java/tipitapi/drawmytoday/user/service/ValidateUserService.java
Labels: 🐞 Bug

#71 서버 생존 검증 api 추가 및 테스트용 토큰 만료 api 테스트 도메인으로 이동
  src/main/java/tipitapi/drawmytoday/DrawMyTodayApplication.java
  src/main/java/tipitapi/drawmytoday/common/config/DevConfig.java
  src/main/java/tipitapi/drawmytoday/common/config/SwaggerConfiguration.java
  src/main/java/tipitapi/drawmytoday/dev/controller/DevelopController.java
  src/main/java/tipitapi/drawmytoday/health/controller/HealthCheckController.java
  src/main/java/tipitapi/drawmytoday/oauth/controller/AuthController.java
Labels: 🔨 Refactor, ✨ Feature

#85 일기 암호화, 복호화시 text 값이 null이면 암호화, 복호화 실패 문제 해결
  .github/workflows/cd.yml
  src/main/java/tipitapi/drawmytoday/common/utils/Encryptor.java
Labels: ⚡ Fix

#88 스웨거 테스트 도메인이 먼저 선택되도록 변경
  src/main/java/tipitapi/drawmytoday/common/config/SwaggerConfiguration.java
Labels: 🔨 Refactor

#86 테스트 환경 Gradle로 변경
  build.gradle
  src/test/resources/application.yml
Labels: 🔧 Setting

#90 일기 생성시 키워드 없이도 생성되도록 변경
  src/main/java/tipitapi/drawmytoday/diary/dto/CreateDiaryRequest.java
  src/main/java/tipitapi/drawmytoday/diary/service/CreateDiaryService.java
  src/main/java/tipitapi/drawmytoday/diary/service/PromptTextService.java
Labels: 🔨 Refactor, ✨ Feature

#92 에러 코드에 이름이 넘어가는 문제 해결 및 일기 생성 제한 해제
  src/main/java/tipitapi/drawmytoday/common/exception/GlobalExceptionHandler.java
  src/main/java/tipitapi/drawmytoday/common/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/tipitapi/drawmytoday/diary/service/CreateDiaryService.java
Labels: 🔨 Refactor, ⚡ Fix

#83 User 엔티티에 Soft delete 애노테이션 추가
  src/main/java/tipitapi/drawmytoday/user/domain/User.java
  src/main/java/tipitapi/drawmytoday/user/repository/UserRepository.java
  src/main/java/tipitapi/drawmytoday/user/service/ValidateUserService.java
  src/test/java/tipitapi/drawmytoday/diary/repository/UserRepositoryTest.java
Labels: ✅ Test, ⚡ Fix
