Repository tipi-tapi/ai-paint-today-BE, pull requests merged in 2023-10, with the labels that each got.

#244 유저 그림 평가시 (GOOD, BAD) 평가 방식에서 1~5 사이의 숫자값을 받도록 수정
  src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
  src/main/java/tipitapi/drawmytoday/domain/diary/controller/DiaryController.java
  src/main/java/tipitapi/drawmytoday/domain/diary/controller/ImageController.java
  src/main/java/tipitapi/drawmytoday/domain/diary/domain/Diary.java
  src/main/java/tipitapi/drawmytoday/domain/diary/domain/Image.java
  src/main/java/tipitapi/drawmytoday/domain/diary/domain/ReviewType.java
  src/main/java/tipitapi/drawmytoday/domain/diary/dto/ReviewDiaryRequest.java
  src/main/java/tipitapi/drawmytoday/domain/diary/exception/NotOwnerOfImageException.java
  src/main/java/tipitapi/drawmytoday/domain/diary/repository/ImageQueryRepository.java
  src/main/java/tipitapi/drawmytoday/domain/diary/repository/ImageQueryRepositoryImpl.java
  src/main/java/tipitapi/drawmytoday/domain/diary/service/DiaryService.java
  src/main/java/tipitapi/drawmytoday/domain/diary/service/ImageService.java
  src/main/java/tipitapi/drawmytoday/domain/diary/service/ValidateImageService.java
  src/test/java/tipitapi/drawmytoday/domain/diary/controller/DiaryControllerTest.java
  src/test/java/tipitapi/drawmytoday/domain/diary/controller/ImageControllerTest.java
  src/test/java/tipitapi/drawmytoday/domain/diary/service/AdminDiaryServiceTest.java
  src/test/java/tipitapi/drawmytoday/domain/diary/service/DiaryServiceTest.java
  src/test/java/tipitapi/drawmytoday/domain/diary/service/ImageServiceTest.java
  src/test/java/tipitapi/drawmytoday/domain/diary/service/PromptTextServiceTest.java
  src/test/resources/tipitapi/drawmytoday/domain/diary/repository/GetDiariesForMonitorAsPageTest.sql
Labels: 🔨 Refactor, ✅ Test

#253 ImageRepository QueryDSL 적용에 따른 이관
  src/main/java/tipitapi/drawmytoday/domain/diary/repository/ImageQueryRepository.java
  src/main/java/tipitapi/drawmytoday/domain/diary/repository/ImageQueryRepositoryImpl.java
  src/main/java/tipitapi/drawmytoday/domain/diary/repository/ImageRepository.java
  src/main/java/tipitapi/drawmytoday/domain/diary/service/ImageService.java
  src/test/java/tipitapi/drawmytoday/domain/diary/repository/ImageRepositoryTest.java
  src/test/java/tipitapi/drawmytoday/domain/diary/service/ImageServiceTest.java
Labels: ⚡ Fix

#257 [월별 일기 반환 API] 대표 이미지가 반환되지 않는 문제 해결
  src/main/java/tipitapi/drawmytoday/domain/diary/domain/Diary.java
  src/main/java/tipitapi/drawmytoday/domain/diary/dto/GetMonthlyDiariesResponse.java
  src/main/java/tipitapi/drawmytoday/domain/diary/repository/DiaryQueryRepository.java
  src/main/java/tipitapi/drawmytoday/domain/diary/repository/DiaryQueryRepositoryImpl.java
  src/main/java/tipitapi/drawmytoday/domain/diary/service/DiaryService.java
  src/test/java/tipitapi/drawmytoday/domain/diary/service/DiaryServiceTest.java
Labels: 🔨 Refactor, ✅ Test

#256 대표 이미지 설정 API 추가
  src/main/java/tipitapi/drawmytoday/domain/diary/controller/ImageController.java
  src/main/java/tipitapi/drawmytoday/domain/diary/service/ImageService.java
  src/main/java/tipitapi/drawmytoday/domain/diary/service/ValidateImageService.java
  src/test/java/tipitapi/drawmytoday/domain/diary/controller/ImageControllerTest.java
  src/test/java/tipitapi/drawmytoday/domain/diary/service/ImageServiceTest.java
Labels: ✨ Feature

#259 [관리자 일기 목록 API] 이미지 평가, 이미지 생성 시간 필드 추가
  src/main/java/tipitapi/drawmytoday/domain/admin/dto/GetDiaryAdminResponse.java
  src/main/java/tipitapi/drawmytoday/domain/diary/repository/DiaryQueryRepositoryImpl.java
  src/test/java/tipitapi/drawmytoday/domain/admin/controller/AdminControllerTest.java
  src/test/java/tipitapi/drawmytoday/domain/admin/service/AdminServiceTest.java
  src/test/java/tipitapi/drawmytoday/domain/diary/service/AdminDiaryServiceTest.java
Labels: ✨ Feature

#260 [월별 일기 목록 API] 대표 이미지가 없을 경우 분기 처리 추가
  src/main/java/tipitapi/drawmytoday/domain/diary/dto/GetMonthlyDiariesResponse.java
  src/main/java/tipitapi/drawmytoday/domain/diary/repository/ImageQueryRepository.java
  src/main/java/tipitapi/drawmytoday/domain/diary/repository/ImageQueryRepositoryImpl.java
  src/main/java/tipitapi/drawmytoday/domain/diary/service/DiaryService.java
  src/main/java/tipitapi/drawmytoday/domain/diary/service/ImageService.java
  src/test/java/tipitapi/drawmytoday/domain/diary/service/DiaryServiceTest.java
Labels: ✅ Test, ✨ Feature

#262 karlo 이미지 파일 확장자 변경
  src/main/java/tipitapi/drawmytoday/domain/diary/service/ImageService.java
  src/main/java/tipitapi/drawmytoday/domain/generator/domain/karlo/dto/CreateKarloImageRequest.java
  src/main/java/tipitapi/drawmytoday/domain/r2/service/R2Service.java
Labels: 🔨 Refactor

#265 테스트 일기 생성 API 구현
  src/main/java/tipitapi/drawmytoday/domain/diary/controller/DiaryController.java
  src/main/java/tipitapi/drawmytoday/domain/diary/controller/TestDiaryController.java
  src/main/java/tipitapi/drawmytoday/domain/diary/dto/CreateTestDiaryRequest.java
  src/main/java/tipitapi/drawmytoday/domain/diary/service/CreateDiaryService.java
  src/main/java/tipitapi/drawmytoday/domain/generator/domain/dalle/service/DallEService.java
  src/main/java/tipitapi/drawmytoday/domain/generator/domain/karlo/dto/CreateKarloImageRequest.java
  src/main/java/tipitapi/drawmytoday/domain/generator/domain/karlo/dto/KarloUrlResponse.java
  src/main/java/tipitapi/drawmytoday/domain/generator/domain/karlo/service/KarloRequestService.java
  src/main/java/tipitapi/drawmytoday/domain/generator/domain/karlo/service/KarloService.java
  src/main/java/tipitapi/drawmytoday/domain/generator/service/ImageGeneratorService.java
Labels: 🔨 Refactor, ✨ Feature

#268 테스트 일기 API 호출시 karlo에 요청할 파라미터 추가
  src/main/java/tipitapi/drawmytoday/domain/diary/dto/CreateTestDiaryRequest.java
  src/main/java/tipitapi/drawmytoday/domain/generator/domain/karlo/dto/CreateKarloImageRequest.java
  src/test/java/tipitapi/drawmytoday/domain/diary/controller/TestDiaryControllerTest.java
  src/test/java/tipitapi/drawmytoday/domain/diary/service/CreateDiaryServiceTest.java
  src/test/java/tipitapi/drawmytoday/domain/generator/domain/karlo/service/KarloRequestServiceTest.java
  src/test/java/tipitapi/drawmytoday/domain/generator/domain/karlo/service/KarloServiceTest.java
Labels: ✅ Test, ✨ Feature
