Repository tipi-tapi/ai-paint-today-BE, pull requests merged in 2023-11, with the labels that each got.

#270 [관리자 일기 조회 API] 테스트 일기가 반환되도록 개선
  src/main/java/tipitapi/drawmytoday/domain/admin/controller/AdminController.java
  src/main/java/tipitapi/drawmytoday/domain/admin/dto/GetDiaryAdminResponse.java
  src/main/java/tipitapi/drawmytoday/domain/admin/service/AdminService.java
  src/main/java/tipitapi/drawmytoday/domain/diary/repository/DiaryQueryRepository.java
  src/main/java/tipitapi/drawmytoday/domain/diary/repository/DiaryQueryRepositoryImpl.java
  src/main/java/tipitapi/drawmytoday/domain/diary/service/AdminDiaryService.java
  src/test/java/tipitapi/drawmytoday/domain/admin/controller/AdminControllerTest.java
  src/test/java/tipitapi/drawmytoday/domain/admin/service/AdminServiceTest.java
  src/test/java/tipitapi/drawmytoday/domain/diary/repository/DiaryRepositoryTest.java
  src/test/java/tipitapi/drawmytoday/domain/diary/service/AdminDiaryServiceTest.java
Labels: ✨ Feature, 1️⃣ P1

#274 프롬프트 개선 작업 서버에 반영
  src/main/java/tipitapi/drawmytoday/domain/diary/service/PromptTextService.java
  src/main/java/tipitapi/drawmytoday/domain/generator/domain/karlo/dto/CreateKarloImageRequest.java
Labels: 🔨 Refactor

#275 Release 1.2.1
  src/main/java/tipitapi/drawmytoday/domain/admin/controller/AdminController.java
  src/main/java/tipitapi/drawmytoday/domain/admin/dto/GetDiaryAdminResponse.java
  src/main/java/tipitapi/drawmytoday/domain/admin/service/AdminService.java
  src/main/java/tipitapi/drawmytoday/domain/diary/controller/DiaryController.java
  src/main/java/tipitapi/drawmytoday/domain/diary/controller/TestDiaryController.java
  src/main/java/tipitapi/drawmytoday/domain/diary/dto/CreateTestDiaryRequest.java
  src/main/java/tipitapi/drawmytoday/domain/diary/repository/DiaryQueryRepository.java
  src/main/java/tipitapi/drawmytoday/domain/diary/repository/DiaryQueryRepositoryImpl.java
  src/main/java/tipitapi/drawmytoday/domain/diary/service/AdminDiaryService.java
  src/main/java/tipitapi/drawmytoday/domain/diary/service/CreateDiaryService.java
  src/main/java/tipitapi/drawmytoday/domain/diary/service/PromptTextService.java
  src/main/java/tipitapi/drawmytoday/domain/emotion/dto/GetActiveEmotionsResponse.java
  src/main/java/tipitapi/drawmytoday/domain/generator/domain/dalle/service/DallEService.java
  src/main/java/tipitapi/drawmytoday/domain/generator/domain/karlo/dto/CreateKarloImageRequest.java
  src/main/java/tipitapi/drawmytoday/domain/generator/domain/karlo/dto/KarloUrlResponse.java
  src/main/java/tipitapi/drawmytoday/domain/generator/domain/karlo/service/KarloRequestService.java
  src/main/java/tipitapi/drawmytoday/domain/generator/domain/karlo/service/KarloService.java
  src/main/java/tipitapi/drawmytoday/domain/generator/service/ImageGeneratorService.java
  src/test/java/tipitapi/drawmytoday/common/testdata/TestDiary.java
  src/test/java/tipitapi/drawmytoday/domain/admin/controller/AdminControllerTest.java
  src/test/java/tipitapi/drawmytoday/domain/admin/service/AdminServiceTest.java
  src/test/java/tipitapi/drawmytoday/domain/diary/controller/DiaryControllerTest.java
  src/test/java/tipitapi/drawmytoday/domain/diary/controller/TestDiaryControllerTest.java
  src/test/java/tipitapi/drawmytoday/domain/diary/repository/DiaryRepositoryTest.java
  src/test/java/tipitapi/drawmytoday/domain/diary/service/AdminDiaryServiceTest.java
  src/test/java/tipitapi/drawmytoday/domain/diary/service/CreateDiaryServiceTest.java
  src/test/java/tipitapi/drawmytoday/domain/diary/service/EmotionServiceTest.java
  src/test/java/tipitapi/drawmytoday/domain/diary/service/ImageServiceTest.java
  src/test/java/tipitapi/drawmytoday/domain/generator/domain/karlo/service/KarloRequestServiceTest.java
  src/test/java/tipitapi/drawmytoday/domain/generator/domain/karlo/service/KarloServiceTest.java
Labels: 🌏 Deploy&Infra

#279 감정 목록 조회시 영어로 응답 통일
  src/main/java/tipitapi/drawmytoday/domain/emotion/controller/EmotionController.java
  src/main/java/tipitapi/drawmytoday/domain/emotion/dto/GetActiveEmotionsResponse.java
  src/main/java/tipitapi/drawmytoday/domain/emotion/service/EmotionService.java
  src/test/java/tipitapi/drawmytoday/domain/emotion/controller/EmotionControllerTest.java
  src/test/java/tipitapi/drawmytoday/domain/emotion/repository/EmotionRepositoryTest.java
  src/test/java/tipitapi/drawmytoday/domain/emotion/service/EmotionServiceTest.java
Labels: ⚡ Fix, ✨ Feature

#277 프롬프트 환경변수화 및 네거티브 프롬프트 추가
  .github/workflows/cd.yml
  src/main/java/tipitapi/drawmytoday/domain/diary/service/PromptTextService.java
  src/main/java/tipitapi/drawmytoday/domain/generator/domain/karlo/dto/CreateKarloImageRequest.java
  src/main/java/tipitapi/drawmytoday/domain/generator/domain/karlo/service/KarloRequestService.java
  src/main/resources/application-kakao.yml
  src/test/java/tipitapi/drawmytoday/domain/generator/domain/karlo/service/KarloRequestServiceTest.java
Labels: 🔨 Refactor, ✅ Test
