Repository tipi-tapi/ai-paint-today-BE, pull requests merged in 2023-08, with the labels that each got.

#154 docker-compose의 컨테이너, db명 수정
  docker-compose.yml
Labels: 🔧 Setting

#155 전체 프롬프트가 1000자를 초과하지 않게 substring 처리
  src/main/java/tipitapi/drawmytoday/diary/service/PromptTextService.java
  src/test/java/tipitapi/drawmytoday/diary/service/PromptTextServiceTest.java
Labels: ✨ Feature

#156 Release 1.0.2
  docker-compose.yml
  src/main/java/tipitapi/drawmytoday/diary/service/PromptTextService.java
  src/test/java/tipitapi/drawmytoday/diary/service/PromptTextServiceTest.java
Labels: 🌏 Deploy&Infra

#161 prompt 테이블의 prompt_text 필드와 emotion 테이블의 color_prompt 필드의 최대 길이 증가
  src/main/java/tipitapi/drawmytoday/diary/domain/Prompt.java
  src/main/java/tipitapi/drawmytoday/emotion/domain/Emotion.java
Labels: ⚡ Fix, 🐞 Bug

#176 모니터링 툴 도입
  build.gradle
  src/main/java/tipitapi/drawmytoday/common/config/SecurityConfig.java
  src/main/resources/application-actuator.yml
  src/main/resources/application.yml
Labels: ✨ Feature

#175 QueryDSL 도입 및 관리자용 일기 목록 조회시 감정 필터링 기능 추가
  build.gradle
  src/main/java/tipitapi/drawmytoday/admin/controller/AdminController.java
  src/main/java/tipitapi/drawmytoday/admin/dto/GetDiaryAdminResponse.java
  src/main/java/tipitapi/drawmytoday/admin/service/AdminService.java
  src/main/java/tipitapi/drawmytoday/common/config/QuerydslConfig.java
  src/main/java/tipitapi/drawmytoday/diary/repository/DiaryQueryRepository.java
  src/main/java/tipitapi/drawmytoday/diary/repository/DiaryQueryRepositoryImpl.java
  src/main/java/tipitapi/drawmytoday/diary/repository/DiaryRepository.java
  src/main/java/tipitapi/drawmytoday/diary/service/AdminDiaryService.java
  src/test/java/tipitapi/drawmytoday/admin/controller/AdminControllerTest.java
  src/test/java/tipitapi/drawmytoday/admin/service/AdminServiceTest.java
  src/test/java/tipitapi/drawmytoday/adreward/repository/AdRewardRepositoryTest.java
  src/test/java/tipitapi/drawmytoday/diary/repository/DiaryRepositoryTest.java
  src/test/java/tipitapi/drawmytoday/diary/repository/EmotionRepositoryTest.java
  src/test/java/tipitapi/drawmytoday/diary/repository/ImageRepositoryTest.java
  src/test/java/tipitapi/drawmytoday/diary/service/AdminDiaryServiceTest.java
  src/test/java/tipitapi/drawmytoday/user/repository/UserRepositoryTest.java
  src/test/resources/tipitapi/drawmytoday/diary/repository/GetDiariesForMonitorAsPageTest.sql
Labels: ⚡ Fix, ✨ Feature

#179 일기 생성시, 주어진 날짜로 생성된 일기가 있는지 검증
  src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
  src/main/java/tipitapi/drawmytoday/common/utils/DateUtils.java
  src/main/java/tipitapi/drawmytoday/diary/exception/DiaryDateAlreadyExistsException.java
  src/main/java/tipitapi/drawmytoday/diary/repository/DiaryQueryRepository.java
  src/main/java/tipitapi/drawmytoday/diary/repository/DiaryQueryRepositoryImpl.java
  src/main/java/tipitapi/drawmytoday/diary/repository/DiaryRepository.java
  src/main/java/tipitapi/drawmytoday/diary/service/CreateDiaryService.java
  src/main/java/tipitapi/drawmytoday/diary/service/DiaryService.java
  src/main/java/tipitapi/drawmytoday/diary/service/ValidateDiaryService.java
  src/test/java/tipitapi/drawmytoday/diary/repository/DiaryRepositoryTest.java
  src/test/java/tipitapi/drawmytoday/diary/service/DiaryServiceTest.java
  src/test/java/tipitapi/drawmytoday/diary/service/ValidateDiaryServiceTest.java
Labels: ⚡ Fix, ✨ Feature

#182 Ticket 엔티티 추가, 회원 가입시 티켓 7개 부여
  src/main/java/tipitapi/drawmytoday/oauth/service/AppleOAuthService.java
  src/main/java/tipitapi/drawmytoday/oauth/service/GoogleOAuthService.java
  src/main/java/tipitapi/drawmytoday/ticket/domain/Ticket.java
  src/main/java/tipitapi/drawmytoday/ticket/domain/TicketType.java
  src/main/java/tipitapi/drawmytoday/ticket/repository/TicketRepository.java
  src/main/java/tipitapi/drawmytoday/ticket/service/TicketService.java
  src/test/java/tipitapi/drawmytoday/ticket/service/TicketServiceTest.java
Labels: ✨ Feature

#186 일기 생성시 Diary 엔티티의 diaryDate에 유저 현재 시각 받아서 저장
  src/main/java/tipitapi/drawmytoday/common/exception/GlobalExceptionHandler.java
  src/main/java/tipitapi/drawmytoday/diary/controller/DiaryController.java
  src/main/java/tipitapi/drawmytoday/diary/domain/Diary.java
  src/main/java/tipitapi/drawmytoday/diary/dto/CreateDiaryRequest.java
  src/main/java/tipitapi/drawmytoday/diary/service/CreateDiaryService.java
  src/main/java/tipitapi/drawmytoday/ticket/service/TicketService.java
  src/test/java/tipitapi/drawmytoday/common/testdata/TestDiary.java
  src/test/java/tipitapi/drawmytoday/diary/controller/DiaryControllerTest.java
  src/test/java/tipitapi/drawmytoday/diary/service/CreateDiaryServiceTest.java
Labels: 🔨 Refactor, ✅ Test

#189 일기 생성시, 광고 리워드가 아닌 티켓을 사용하도록 개선
  src/main/java/tipitapi/drawmytoday/adreward/service/UseAdRewardService.java
  src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
  src/main/java/tipitapi/drawmytoday/diary/controller/DiaryController.java
  src/main/java/tipitapi/drawmytoday/diary/service/CreateDiaryService.java
  src/main/java/tipitapi/drawmytoday/ticket/exception/ValidTicketNotExistsException.java
  src/main/java/tipitapi/drawmytoday/ticket/service/ValidateTicketService.java
  src/main/java/tipitapi/drawmytoday/user/service/ValidateUserService.java
  src/test/java/tipitapi/drawmytoday/adreward/service/UseAdRewardServiceTest.java
  src/test/java/tipitapi/drawmytoday/diary/service/CreateDiaryServiceTest.java
  src/test/java/tipitapi/drawmytoday/ticket/service/ValidateTicketServiceTest.java
Labels: ✨ Feature

#190 Release 1.1.0
  build.gradle
  src/main/java/tipitapi/drawmytoday/admin/controller/AdminController.java
  src/main/java/tipitapi/drawmytoday/admin/dto/GetDiaryAdminResponse.java
  src/main/java/tipitapi/drawmytoday/admin/service/AdminService.java
  src/main/java/tipitapi/drawmytoday/adreward/service/AdRewardService.java
  src/main/java/tipitapi/drawmytoday/adreward/service/UseAdRewardService.java
  src/main/java/tipitapi/drawmytoday/common/config/QuerydslConfig.java
  src/main/java/tipitapi/drawmytoday/common/config/SecurityConfig.java
  src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
  src/main/java/tipitapi/drawmytoday/common/exception/GlobalExceptionHandler.java
  src/main/java/tipitapi/drawmytoday/common/utils/DateUtils.java
  src/main/java/tipitapi/drawmytoday/diary/controller/DiaryController.java
  src/main/java/tipitapi/drawmytoday/diary/domain/Diary.java
  src/main/java/tipitapi/drawmytoday/diary/dto/CreateDiaryRequest.java
  src/main/java/tipitapi/drawmytoday/diary/dto/GetDiaryLimitResponse.java
  src/main/java/tipitapi/drawmytoday/diary/exception/DiaryDateAlreadyExistsException.java
  src/main/java/tipitapi/drawmytoday/diary/repository/DiaryQueryRepository.java
  src/main/java/tipitapi/drawmytoday/diary/repository/DiaryQueryRepositoryImpl.java
  src/main/java/tipitapi/drawmytoday/diary/repository/DiaryRepository.java
  src/main/java/tipitapi/drawmytoday/diary/service/AdminDiaryService.java
  src/main/java/tipitapi/drawmytoday/diary/service/CreateDiaryService.java
  src/main/java/tipitapi/drawmytoday/diary/service/DiaryService.java
  src/main/java/tipitapi/drawmytoday/diary/service/ValidateDiaryService.java
  src/main/java/tipitapi/drawmytoday/oauth/service/AppleOAuthService.java
  src/main/java/tipitapi/drawmytoday/oauth/service/GoogleOAuthService.java
  src/main/java/tipitapi/drawmytoday/ticket/domain/Ticket.java
  src/main/java/tipitapi/drawmytoday/ticket/domain/TicketType.java
  src/main/java/tipitapi/drawmytoday/ticket/exception/ValidTicketNotExistsException.java
  src/main/java/tipitapi/drawmytoday/ticket/repository/TicketQueryRepository.java
  src/main/java/tipitapi/drawmytoday/ticket/repository/TicketQueryRepositoryImpl.java
  src/main/java/tipitapi/drawmytoday/ticket/repository/TicketRepository.java
  src/main/java/tipitapi/drawmytoday/ticket/service/TicketService.java
  src/main/java/tipitapi/drawmytoday/ticket/service/ValidateTicketService.java
  src/main/java/tipitapi/drawmytoday/user/service/ValidateUserService.java
  src/main/resources/application-actuator.yml
  src/main/resources/application.yml
  src/test/java/tipitapi/drawmytoday/admin/controller/AdminControllerTest.java
  src/test/java/tipitapi/drawmytoday/admin/service/AdminServiceTest.java
  src/test/java/tipitapi/drawmytoday/adreward/repository/AdRewardRepositoryTest.java
  src/test/java/tipitapi/drawmytoday/adreward/service/AdRewardServiceTest.java
  src/test/java/tipitapi/drawmytoday/adreward/service/UseAdRewardServiceTest.java
  src/test/java/tipitapi/drawmytoday/common/testdata/TestDiary.java
  src/test/java/tipitapi/drawmytoday/diary/controller/DiaryControllerTest.java
  src/test/java/tipitapi/drawmytoday/diary/repository/DiaryRepositoryTest.java
  src/test/java/tipitapi/drawmytoday/diary/repository/EmotionRepositoryTest.java
  src/test/java/tipitapi/drawmytoday/diary/repository/ImageRepositoryTest.java
  src/test/java/tipitapi/drawmytoday/diary/service/AdminDiaryServiceTest.java
  src/test/java/tipitapi/drawmytoday/diary/service/CreateDiaryServiceTest.java
  src/test/java/tipitapi/drawmytoday/diary/service/DiaryServiceTest.java
  src/test/java/tipitapi/drawmytoday/diary/service/ValidateDiaryServiceTest.java
  src/test/java/tipitapi/drawmytoday/ticket/repository/TicketRepositoryTest.java
  src/test/java/tipitapi/drawmytoday/ticket/service/TicketServiceTest.java
  src/test/java/tipitapi/drawmytoday/ticket/service/ValidateTicketServiceTest.java
  src/test/java/tipitapi/drawmytoday/user/repository/UserRepositoryTest.java
  src/test/resources/tipitapi/drawmytoday/diary/repository/GetDiariesForMonitorAsPageTest.sql
  src/test/resources/tipitapi/drawmytoday/ticket/repository/ValidTicket.sql
Labels: 🌏 Deploy&Infra

#191 일기 생성 시 오늘 날짜의 일기가 없을 때만 일기 작성할 수 있도록 수정
  src/main/java/tipitapi/drawmytoday/diary/service/ValidateDiaryService.java
Labels: 🐞 Bug

#192 일기 생성 시 오늘 날짜의 일기가 없을 때만 일기 작성할 수 있도록 수정
  src/main/java/tipitapi/drawmytoday/diary/service/ValidateDiaryService.java
Labels: 🐞 Bug

#199 S3 로직 제거, R2 Presigned URL 발급 로직 적용
  src/main/java/tipitapi/drawmytoday/common/config/R2Config.java
  src/main/java/tipitapi/drawmytoday/common/config/S3Config.java
  src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
  src/main/java/tipitapi/drawmytoday/common/exception/GlobalExceptionHandler.java
  src/main/java/tipitapi/drawmytoday/diary/service/AdminDiaryService.java
  src/main/java/tipitapi/drawmytoday/diary/service/DiaryService.java
  src/main/java/tipitapi/drawmytoday/diary/service/ImageService.java
  src/main/java/tipitapi/drawmytoday/r2/exception/R2FailedException.java
  src/main/java/tipitapi/drawmytoday/r2/service/R2PreSignedService.java
  src/main/java/tipitapi/drawmytoday/r2/service/R2Service.java
  src/main/java/tipitapi/drawmytoday/s3/exception/S3FailedException.java
  src/main/java/tipitapi/drawmytoday/s3/service/S3PreSignedService.java
  src/main/java/tipitapi/drawmytoday/s3/service/S3Service.java
  src/main/java/tipitapi/drawmytoday/s3/service/S3Util.java
  src/test/java/tipitapi/drawmytoday/diary/service/AdminDiaryServiceTest.java
  src/test/java/tipitapi/drawmytoday/diary/service/DiaryServiceTest.java
  src/test/java/tipitapi/drawmytoday/diary/service/ImageServiceTest.java
  src/test/java/tipitapi/drawmytoday/diary/service/ValidateDiaryServiceTest.java
  src/test/resources/application.yml
Labels: 🌏 Deploy&Infra, ✅ Test, ⚡ Fix

#200 Release 1.1.2
  src/main/java/tipitapi/drawmytoday/common/config/R2Config.java
  src/main/java/tipitapi/drawmytoday/common/config/S3Config.java
  src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
  src/main/java/tipitapi/drawmytoday/common/exception/GlobalExceptionHandler.java
  src/main/java/tipitapi/drawmytoday/diary/service/AdminDiaryService.java
  src/main/java/tipitapi/drawmytoday/diary/service/DiaryService.java
  src/main/java/tipitapi/drawmytoday/diary/service/ImageService.java
  src/main/java/tipitapi/drawmytoday/r2/exception/R2FailedException.java
  src/main/java/tipitapi/drawmytoday/r2/service/R2PreSignedService.java
  src/main/java/tipitapi/drawmytoday/r2/service/R2Service.java
  src/main/java/tipitapi/drawmytoday/s3/exception/S3FailedException.java
  src/main/java/tipitapi/drawmytoday/s3/service/S3PreSignedService.java
  src/main/java/tipitapi/drawmytoday/s3/service/S3Service.java
  src/main/java/tipitapi/drawmytoday/s3/service/S3Util.java
  src/test/java/tipitapi/drawmytoday/diary/service/AdminDiaryServiceTest.java
  src/test/java/tipitapi/drawmytoday/diary/service/DiaryServiceTest.java
  src/test/java/tipitapi/drawmytoday/diary/service/ImageServiceTest.java
  src/test/java/tipitapi/drawmytoday/diary/service/ValidateDiaryServiceTest.java
  src/test/resources/application.yml
Labels: 🌏 Deploy&Infra

#205 QType에 domain 패키지로 도메인 코드 이동 반영
  src/main/java/tipitapi/drawmytoday/domain/admin/controller/AdminController.java
  src/main/java/tipitapi/drawmytoday/domain/adreward/controller/AdRewardController.java
  src/main/java/tipitapi/drawmytoday/domain/adreward/service/AdRewardService.java
  src/main/java/tipitapi/drawmytoday/domain/diary/repository/DiaryQueryRepositoryImpl.java
  src/main/java/tipitapi/drawmytoday/domain/diary/service/CreateDiaryService.java
  src/main/java/tipitapi/drawmytoday/domain/diary/service/DiaryService.java
  src/main/java/tipitapi/drawmytoday/domain/emotion/service/EmotionService.java
  src/main/java/tipitapi/drawmytoday/domain/emotion/service/ValidateEmotionService.java
  src/main/java/tipitapi/drawmytoday/domain/oauth/controller/AuthController.java
  src/main/java/tipitapi/drawmytoday/domain/oauth/service/AppleOAuthService.java
  src/main/java/tipitapi/drawmytoday/domain/oauth/service/GoogleOAuthService.java
  src/main/java/tipitapi/drawmytoday/domain/oauth/service/OAuthService.java
  src/main/java/tipitapi/drawmytoday/domain/ticket/repository/TicketQueryRepositoryImpl.java
  src/main/java/tipitapi/drawmytoday/domain/ticket/service/TicketService.java
  src/main/java/tipitapi/drawmytoday/domain/user/service/UserService.java
  src/main/java/tipitapi/drawmytoday/domain/user/service/ValidateUserService.java
  src/test/java/tipitapi/drawmytoday/admin/controller/AdminControllerTest.java
  src/test/java/tipitapi/drawmytoday/adreward/controller/AdRewardControllerTest.java
  src/test/java/tipitapi/drawmytoday/adreward/repository/AdRewardRepositoryTest.java
  src/test/java/tipitapi/drawmytoday/diary/repository/DiaryRepositoryTest.java
Labels: 🧼 CleanUp

#206 JACOCO 커버리지 Q파일 제거
  build.gradle
Labels: 🔧 Setting

#209 README.md 개선
  README.md
  docs/convention.md
  docs/dev_setting.md
  docs/dev_wiki.md
  docs/package_structure.md
  docs/service_detail.md
Labels: 📃 Docs

#212 DALL-E 컨텐츠 정책 에러 발생시 재시도
  src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
  src/main/java/tipitapi/drawmytoday/dalle/dto/GeneratedImageAndPrompt.java
  src/main/java/tipitapi/drawmytoday/dalle/exception/DallEException.java
  src/main/java/tipitapi/drawmytoday/dalle/exception/DallERequestFailException.java
  src/main/java/tipitapi/drawmytoday/dalle/exception/ImageInputStreamFailException.java
  src/main/java/tipitapi/drawmytoday/dalle/service/DallEService.java
  src/main/java/tipitapi/drawmytoday/diary/controller/DiaryController.java
  src/main/java/tipitapi/drawmytoday/diary/service/CreateDiaryService.java
  src/test/java/tipitapi/drawmytoday/diary/service/CreateDiaryServiceTest.java
Labels: ⚡ Fix, 🐞 Bug

#213 DALL-E 컨텐츠 정책 에러 발생시 재시도
  src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
  src/main/java/tipitapi/drawmytoday/domain/dalle/dto/GeneratedImageAndPrompt.java
  src/main/java/tipitapi/drawmytoday/domain/dalle/exception/DallEException.java
  src/main/java/tipitapi/drawmytoday/domain/dalle/exception/DallERequestFailException.java
  src/main/java/tipitapi/drawmytoday/domain/dalle/exception/ImageInputStreamFailException.java
  src/main/java/tipitapi/drawmytoday/domain/dalle/service/DallEService.java
  src/main/java/tipitapi/drawmytoday/domain/diary/controller/DiaryController.java
  src/main/java/tipitapi/drawmytoday/domain/diary/service/CreateDiaryService.java
  src/test/java/tipitapi/drawmytoday/diary/service/CreateDiaryServiceTest.java
Labels: ⚡ Fix, 🐞 Bug

#216 일기 생성 플로우 리드미 추가
  README.md
Labels: 📃 Docs

#218 OAuthService 리팩토링 및 User 엔티티 email 필드 not nullable
  src/main/java/tipitapi/drawmytoday/common/exception/ErrorCode.java
  src/main/java/tipitapi/drawmytoday/common/utils/HeaderUtils.java
  src/main/java/tipitapi/drawmytoday/domain/oauth/controller/AuthController.java
  src/main/java/tipitapi/drawmytoday/domain/oauth/domain/Auth.java
  src/main/java/tipitapi/drawmytoday/domain/oauth/service/AppleOAuthService.java
  src/main/java/tipitapi/drawmytoday/domain/oauth/service/GoogleOAuthService.java
  src/main/java/tipitapi/drawmytoday/domain/user/domain/User.java
  src/main/java/tipitapi/drawmytoday/domain/user/service/UserService.java
Labels: 🔨 Refactor

#220 auth 도메인 서비스단 테스트코드 작성
  src/main/java/tipitapi/drawmytoday/domain/user/domain/User.java
  src/main/java/tipitapi/drawmytoday/domain/user/service/UserService.java
  src/test/java/tipitapi/drawmytoday/common/testdata/TestAuth.java
  src/test/java/tipitapi/drawmytoday/common/testdata/TestUser.java
  src/test/java/tipitapi/drawmytoday/domain/oauth/service/AppleOAuthServiceTest.java
  src/test/java/tipitapi/drawmytoday/domain/oauth/service/GoogleOAuthServiceTest.java
  src/test/java/tipitapi/drawmytoday/domain/oauth/service/OAuthServiceTest.java
  src/test/java/tipitapi/drawmytoday/user/repository/UserRepositoryTest.java
  src/test/resources/tipitapi/drawmytoday/adreward/repository/ExpiredAdReward.sql
  src/test/resources/tipitapi/drawmytoday/adreward/repository/ValidAdReward.sql
  src/test/resources/tipitapi/drawmytoday/diary/repository/GetDiariesForMonitorAsPageTest.sql
  src/test/resources/tipitapi/drawmytoday/ticket/repository/ValidTicket.sql
Labels: 🔨 Refactor, ✅ Test

#224 감정 목록 조회 API Language enum 적용
  src/main/java/tipitapi/drawmytoday/domain/emotion/controller/EmotionController.java
  src/main/java/tipitapi/drawmytoday/domain/emotion/dto/GetActiveEmotionsResponse.java
  src/main/java/tipitapi/drawmytoday/domain/emotion/service/EmotionService.java
  src/test/java/tipitapi/drawmytoday/domain/diary/service/EmotionServiceTest.java
  src/test/java/tipitapi/drawmytoday/domain/emotion/controller/EmotionControllerTest.java
Labels: 🔨 Refactor, ⚡ Fix

#225 모든 감정 조회 api에 캐싱 도입
  build.gradle
  src/main/java/tipitapi/drawmytoday/common/cache/CacheConst.java
  src/main/java/tipitapi/drawmytoday/common/cache/CacheType.java
  src/main/java/tipitapi/drawmytoday/common/config/CacheConfig.java
  src/main/java/tipitapi/drawmytoday/domain/emotion/service/EmotionService.java
Labels: ✨ Feature
